@startuml
'https://plantuml.com/sequence-diagram

participant EntityRenderer
participant TerrainRenderer

collections GBuffer

participant CompositeSystem

collections GBufferComposite

participant GuiSystem

EntityRenderer -> GBuffer
TerrainRenderer -> GBuffer

GBuffer -> CompositeSystem

CompositeSystem -> GBufferComposite

GBufferComposite ->














@enduml