@startuml
'https://plantuml.com/sequence-diagram

autonumber


box "GBuffer" #LightBlue
participant Depth
participant Albedo
participant Depth


end box


Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response



@enduml