
set(SLANG_ENABLE_CUDA OFF)
set(SLANG_ENABLE_OPTIX OFF)
set(SLANG_ENABLE_NVAPI OFF)

set(SLANG_ENABLE_AFTERMATH OFF)
set(SLANG_ENABLE_DX_ON_VK OFF)
set(SLANG_EMBED_CORE_MODULE_SOURCE OFF)
set(SLANG_EMBED_CORE_MODULE ON)

set(SLANG_ENABLE_DXIL OFF)
set(SLANG_ENABLE_FULL_IR_VALIDATION ON)
set(SLANG_ENABLE_IR_BREAK_ALLOC ON)

set(SLANG_ENABLE_PREBUILD_BINARIES OFF)
set(SLANG_ENABLE_GFX OFF)

set(SLANG_ENABLE_SLANGD OFF)
set(SLANG_ENABLE_SHANGC OFF)
set(SLANG_ENABLE_TESTS OFF)
set(SLANG_ENABLE_EXAMPLES OFF)

set(SLANG_ENABLE_GFX OFF)

set(SLANG_USE_SYSTEM_VULKAN_HEADERS OFF)

set(SLANG_ENABLE_SPLIT_DEBUG_INFO OFF)
set(SLANG_ENABLE_RELEASE_DEBUG_INFO OFF)
set(SLANG_ENABLE_RELEASE_LTO ON)

add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/dependencies/slang)