

string(TOUPPER ${CMAKE_BUILD_TYPE} CMAKE_UPPER_BUILD_TYPE)

message("-- Cmake upper: ${CMAKE_UPPER_BUILD_TYPE}")


#if (CMAKE_UPPER_BUILD_TYPE STREQUAL "DEBUG" OR CMAKE_UPPER_BUILD_TYPE STREQUAL "RELWITHDEBINFO" AND DEFINED FGL_ENABLE_PROFILING)
if (FGL_ENABLE_PROFILING)
	set(TRACY_ENABLE ON)
	set(TRACY_ON_DEMAND ON)
	set(TRACY_NO_EXIT ON)
else ()
	set(TRACY_ENABLE OFF)
endif ()

add_subdirectory(${CMAKE_SOURCE_DIR}/dependencies/tracy)

